INSERT INTO Department(dID, name) VALUES
(1, 'Accounting'),
(2, 'Africana Studies'),
(117, 'Anatomy'),
(3, 'Anthropology'),
(118, 'Arabic'),
(4, 'Architecture'),
(54, 'Art History'),
(5, 'Athletics'),
(55, 'Behavioral Health Counseling Services'),
(6, 'Biological Sciences'),
(7, 'Bioscience and Biotech'),
(8, 'Business and Admin'),
(58, 'Career Integrated Education'),
(59, 'Certificate in Integrative Therapies'),
(9, 'Chemical Engineering'),
(10, 'Chemistry'),
(57, 'Chinese'),
(12, 'CoMAD'),
(56, 'Communication and Applied Technology'),
(119, 'Complemention and Integration'),
(13, 'Computer Engineering'),
(14, 'Computer Science'),
(62, 'Computing Technology'),
(15, 'Construction Management'),
(120, 'Creative Studies'),
(60, 'Criminal Justice'),
(63, 'Culinary Arts'),
(16, 'Culture and Communication'),
(64, 'Dance'),
(17, 'Decision Sciences'),
(18, 'Design  Economics'),
(66, 'Design and Merchandising'),
(65, 'Digital Media'),
(50, 'Economics'),
(19, 'Education'),
(69, 'Educational Administration'),
(20, 'Electrical Engineering'),
(11, 'Engineer Civil and Arch. Engineer'),
(21, 'Engineering'),
(71, 'Engineering Management'),
(22, 'English and Philosophy'),
(67, 'Entertainment and Arts Management'),
(72, 'Environmental Engineering'),
(73, 'Environmental Policy'),
(23, 'Environmental Science'),
(96, 'Epidemiology'),
(24, 'Evening Studies'),
(25, 'Fashion Design'),
(74, 'Film and Video'),
(26, 'Finance'),
(88, 'Forensic Science'),
(75, 'French'),
(76, 'German'),
(70, 'Global and International Education'),
(114, 'Graphic Design'),
(77, 'Greek'),
(27, 'Health Professions'),
(28, 'History and Politics'),
(29, 'Hospitality Management'),
(78, 'Hotel and Restaurant Management'),
(79, 'Human Resource Management'),
(30, 'Info Science and Technology'),
(80, 'Interior Design'),
(38, 'International Studies'),
(81, 'Italian'),
(82, 'Japanese'),
(83, 'Korean'),
(84, 'Law'),
(39, 'Legal Studies'),
(85, 'Linguistics'),
(41, 'Management'),
(40, 'Management Information Systems'),
(87, 'Manufacturing Engineering'),
(42, 'Marketing'),
(52, 'Materials Engineering'),
(43, 'Mathematics'),
(44, 'Mechanical Engineering'),
(86, 'Medical Billing'),
(89, 'Music'),
(90, 'Neuroscience'),
(53, 'Nursing'),
(91, 'Nutrition and Food Science'),
(92, 'Operations Management'),
(93, 'Operations Research'),
(94, 'Organizational Behavior'),
(49, 'Other'),
(45, 'Performance Arts'),
(98, 'Photography'),
(102, 'Physical Therapy'),
(95, 'Physician Assistant'),
(46, 'Physics'),
(97, 'Physiology'),
(101, 'Political Science'),
(100, 'Production Operations Management'),
(61, 'Professional Studies'),
(47, 'Psychology'),
(99, 'Publication Management'),
(103, 'Radiologic Sciences'),
(104, 'Russian'),
(105, 'Screenwriting and Playwriting'),
(48, 'Sociology'),
(106, 'Software Engineering'),
(108, 'Spanish'),
(107, 'Sport Management'),
(109, 'Statistics'),
(110, 'Taxation'),
(68, 'Telecommunications'),
(112, 'Television Management'),
(111, 'Theatre'),
(113, 'University Courses'),
(51, 'Visual Studies'),
(115, 'Women Studies'),
(116, 'Writing');
